### ISSUE TITLE
Parallel RabbitMQ connection termination

### ISSUE THREAD

**Issue by SuperFunks** [logstash-plugins/logstash-input-rabbitmq#110]
Hi there,

I've been observing the shutdown logs happening in Logstash when a "logstash-input-rabbitmq" has alot of connections going to a rabbitmq cluster.
From what i can tell - the logstash attempts to terminate the connections in sequence, with the same timeout for all connections. This means that it will take a long time for logstash to finally terminate its processes.

[2018-02-27T17:41:58,268][INFO ][logstash.inputs.rabbitmq ] Waiting for rabbitmq consumer to terminate before stopping!

I was wondering if it could be possible to enable Parallel RabbitMQ connection termination, to speed up the Logstash shutdown process?`

Using Logstash 6.2.2 with latest logstash-input-rabbitmq plugin.

Best regards.

**Comment by yaauie** [comment]
It looks like this issue isn't something that can be fixed directly in this code-base, so I have filed an issue upstream on logstash core:

https://github.com/elastic/logstash/issues/11336
