### ISSUE TITLE
SSL InvalidAlgorithmParameterException

### ISSUE THREAD

**Issue by Woudan** [logstash-plugins/logstash-input-rabbitmq#113]
- Version: Logstash 6.3.0
- Operating System: Centos 7.4
- Config File (if you have sensitive info, please remove it):
`input {
  rabbitmq {
    queue => "X"
    host => "X"
    port => "5671"
    ssl => true
    ssl_certificate_path => "/etc/pki/x/x.pfx"
    ssl_certificate_password => ""
    vhost => "/logstash"
    user => "logstash"
    password => "X"
    passive => true
    connection_timeout => 1000
  }
}`
- Error:
[2018-06-26T08:18:44,502][ERROR][logstash.inputs.rabbitmq ] RabbitMQ connection error, will retry. {:error_message=>"java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty", :exception=>"Java::JavaxNetSsl::SSLException"}
- java version:
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)

Description:
When setting up the logstash rabbitmq input plugin with SSL i get the error above.

Is this broken in logstash 6.3.0 or could this be a java version/dependency issue?

**Comment by jsvd** [comment]
can we confirm the user that runs logstash (likely `logstash`) has permissions to open the certificate?
also, for context, is this something that used to work before but broke in 6.3.0?

**Comment by sigsegv11** [comment]
Hi 
Turns out the pkcs12 format expected by java is a bit different from the one generated by openssl. 
Using keytool with storetype PKCS12 solves the issue.
For example:
 `keytool -importcert -file certs/rootCA.crt -trustcacerts -keystore keystore -storetype PKCS12`
