### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by michaelklishin** [logstash-plugins/logstash-input-rabbitmq#124]
I have submitted a pull request that corrects a counterproductive recommendation meant to be copied-and-pasted in this project's doc guide https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/121. It was approved and has been sitting there since.

Is this project maintained? If so, who are the maintainers? If not, what was it superseded by? Some clarification would be great.

**Comment by jsvd** [comment]
hi @michaelklishin, I guess one more time apologies for the delays, as we've been a bit stretched thin for the past few weeks.

For context, we're trying to reduce the effort of maintenance of plugins so we're grouping similar plugins into "integration" plugins. and have used rabbitmq as the first one (see https://github.com/logstash-plugins/logstash-integration-rabbitmq).

This repo has both the input and the output combined into 1 repository, so the next step is adding the messaging here about how new issues/prs must be moved to the that repo, except for critical issues or important documentation changes.

**Comment by michaelklishin** [comment]
@jsvd so I should resubmit to the new repository. OK, thanks for the clarification.
