### ISSUE TITLE
Unable to connect using TLS1.1 or TLS1.2

### ISSUE THREAD

**Issue by timblackwell** [logstash-plugins/logstash-input-rabbitmq#16]
The rabbitmq plugin can't negotiate a ssl connection using a secure TLS protocol version (1.1 or 1.2).
The logstash client (version 1.4.2 running on Yosemite 10.10.2) displays the `error RabbitMQ connection error: Received fatal alert: protocol_version. Will reconnect in 10 seconds... {:level=>:error}` 
The logs from the RabbitMQ server (version 3.4.3, Erlang 17.4) show that the client was trying to connect with TLS1.

If the RabbitMQ configuration file is changed to accept TLS1, logstash can connect.

Can support for TLS1.1 or TLS1.2 be added as according to RabbitMQ documentation, they are the only secure versions.

**Comment by michaelklishin** [comment]
It can but JDK 6 only supports TLS 1.0. Are we ready to require JDK 7?

This would also require a couple of improvements in March Hare to make this easier (than messing with an `SSLContext`) to configure.

**Comment by jordansissel** [comment]
@michaelklishin as it turns out, Logstash is only supported on Java 7 and Java 8. I don't know if this is documented explicitly in the Logstash docs. Java 7 is nearly EOL (April 2015). Java 6 was EOL'd 2.5 years ago (November 2012, I think?).

**Comment by jordansissel** [comment]
Also, regarding TLS 1.2. JRuby doesn't support this at this time, so I think the highest you get is TLS 1.1.

**Comment by michaelklishin** [comment]
@jordansissel it's not unreasonable to drop JDK 6 support. I'll work on getting the version options into March Hare.

**Comment by timblackwell** [comment]
@michaelklishin How long do you think this update will take?

**Comment by jsvd** [comment]
we now recommend/run java 7 or 8, I think we can close this
