### ISSUE TITLE
Documentation doesn't show requirement of having all arguments of queue explicitly specified in config

### ISSUE THREAD

**Issue by dellis23** [logstash-plugins/logstash-input-rabbitmq#20]
On attempting to pull from a queue that has been already defined, the plugin will fail if there are additional settings on the queue, such as `x-max-length`.  Is this a standard rabbit-ism?  It seems like the consumer should be completely agnostic to server-side settings like queue length.

**Comment by dellis23** [comment]
The failure condition logs something like this: 

```{:timestamp=>"2015-04-07T10:20:32.874000-0700", :message=>"RabbitMQ connection error: PRECONDITION_FAILED - inequivalent arg 'x-max-length'for queue 'myqueue' in vhost 'myvhost': received none but current is the value '400000' of type 'long'. Will reconnect in 10 seconds...", :level=>:error}```

**Comment by michaelklishin** [comment]
When re-declaring an existing queue, you must specify the same arguments or use `passive: true` (which would do nothing if the queue exists).

**Comment by michaelklishin** [comment]
Logstash consumer cannot assume the queue was declared. So it tries to declare it. It can be made smarter (check if it exists first) but then you'd have another problem: you specify some arguments but they are "not applied".

**Comment by dellis23** [comment]
I see.  The `passive: true` option makes sense and should have been what I tried.
