### ISSUE TITLE
Fails with error if input is array of json data at top level

### ISSUE THREAD

**Issue by luckyhughes** [logstash-plugins/logstash-input-rabbitmq#21]
Hi,

I was using this plugin to build scalable log management system. I am facing a issue if data received by this plugin from rabbitmq is array of josn at top level as described. please help me how can i fix this issue. Any help in this regard would be appreciated.

json format -
[
{"name":"java.lang:type=OperatingSystem-TotalSwapSpaceSize","value":2147483648},{"name":"java.lang:type=OperatingSystem-FreeSwapSpaceSize","value":671612928},{"name":"java.lang:type=OperatingSystem-ProcessCpuTime","value":11065977}
]

**Comment by untergeek** [comment]
Is that supposed to be 3 separate events?  I don't think this will work within the Logstash event framework at the top level.  I think your options include:

* Create a `json_array` codec based on the [json_lines](https:github.com/logstash-plugins/logstash-codec-json_lines) or [json](https:github.com/logstash-plugins/logstash-codec-json) codecs.  This codec would expect an array of json lines, and send them through as individual events.  This codec could even `require` the json_lines codec and just work on top of that.
* Parse into individual events/json lines before sending to Logstash.

**Comment by andrewvc** [comment]
This thread seems dead, closing.
