### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by iemem15** [logstash-plugins/logstash-input-rabbitmq#23]
When there is a disconnect in the rabbitmq it creates tons of connections, every 10 secondes
In the file logstash-input-rabbitmq-0.1.4-java/lib/logstash/inputs/rabbitmq/march_hare.rb 
it has :automatic_recovery => false

I read that this fixed that.
The version of logstash 1.5.0.rc3
Thanks in advanced

**Comment by andrewvc** [comment]
@iemem15 I'm working on fixing this as we speak :)

**Comment by andrewvc** [comment]
This has been fixed for a while now.
