### ISSUE TITLE
RabbitMQ message properties cannot be read

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-rabbitmq#24]
(This issue was originally filed by @Fresa at https://github.com/elastic/logstash/issues/2069)

---

There does not seem to be a way to include the message properties from a RabbitMQ message into logstash? Headers, message id and correlation id for example.

**Comment by BDeus** [comment]
I'm not a ruby expert but it seems that the march_hare plugin used by logstash-input-rabbitmq can't retrieve message properties to consumers (like original routing key).

**Comment by michaelklishin** [comment]
Yes, [it can](https://github.com/ruby-amqp/march_hare/blob/master/spec/higher_level_api/integration/message_metadata_access_spec.rb#L12). Small nit pick: routing key is not a message property, it's a part of the delivery metadata.

**Comment by andrewvc** [comment]
This has been fixed in https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/65
