### ISSUE TITLE
Improve RabbitMQ input and output plugin docs

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-rabbitmq#25]
(This issue was originally filed by @deepybee at https://github.com/elastic/logstash/issues/2133)

---

Just a minor improvement, but when setting up an output to a RabbitMQ broker yesterday I ran into an issue which was not immediately obvious given the socket connection errors returned by March Hare.

The issue was that in my config I had specified a vhost including the leading forward slash "/"

The documentation only states that a vhost entry should be a string and that the default is "/" - it would be handy if this were amended to clarify a non default vhost should not contain any leading slash.

**Comment by magnusbaeck** [comment]
This issue was addressed with https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/15 so it can be closed.

**Comment by wiibaa** [comment]
@suyograo can you close please
