### ISSUE TITLE
support ssl client certificate

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-rabbitmq#27]
(This issue was originally filed by @runningman84 at https://github.com/elastic/logstash/issues/2394)

---

I would like to auth with RabbitMQ using a ssl client key. This is the same concept as sensu is doing:
http://sensuapp.org/docs/0.16/certificates

**Comment by Semyazz** [comment]
+1

**Comment by jmparra** [comment]
why isn't implemented? https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/commit/89cc1a8e1042d8db873b5f188162bdd937e1dbdf

**Comment by andrewvc** [comment]
@jmparra you're right this should work. Our docs are out of date because doc regeneration is partially broken. Closing because this has worked as you pointed out in https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/commit/89cc1a8e1042d8db873b5f188162bdd937e1dbdf
