### ISSUE TITLE
inputs rabbitmq plugin

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-rabbitmq#28]
(This issue was originally filed by @plejik at https://github.com/elastic/logstash/issues/2895)

---

I create config for logstash rabbitmq plugin
        rabbitmq {
                host => "10.12.42.171"
                queue => "logstash-queue"
                passive => true
                durable => true
                user => "logstash"
                password => "logstash"
                vhost => "/logstash"
                key => "logstash-key"
                exchange => "logs"
        }
When start its try to connect to not existed queue. In docs i found that :
"
The default settings will create an entirely transient queue and listen for all messages by default. If you need durability or any other advanced settings, please set the appropriate options
"
and while i did not create by my hand, i will receive error that queue dosent exist.
Can someone tell me if rabbitmq plugins must create queue by himself or not?

**Comment by michaelklishin** [comment]
It should and [it does](https://github.com/logstash-plugins/logstash-input-rabbitmq/blob/master/lib/logstash/inputs/rabbitmq/march_hare.rb#L94-99). Please post more details, in particular the error message you're seeing and what's in RabbitMQ log file.

**Comment by wiibaa** [comment]
stall answered question 
@suyograo can you close please

**Comment by andrewvc** [comment]
Closed due to lack of info
