### ISSUE TITLE
logstash couldn't show the content of the rabbit message

### ISSUE THREAD

**Issue by baoyonglei** [logstash-plugins/logstash-input-rabbitmq#31]
I create config for logstash rabbitmq plugin
 rabbitmq {
         host => "xx.xx.xx.xxx"
         user => "rabbit"
         password => "xxxxxxxxxxxxxx"
         exchange => "nova"
         key => "#"
         queue => "logstash-queue"
         durable => true
    }

then start logstash, it does work and can collect rabbitmq message.  but can't show the content, just show like this (I use stdout output):
    2015-07-17T15:51:13.767+0000 %{host} %{message}
    2015-07-17T15:51:13.836+0000 %{host} %{message}
    2015-07-17T15:51:13.872+0000 %{host} %{message}"

Why so?

**Comment by andrewvc** [comment]
@baoyonglei you want to try and inspect  the message with the 'rubydebug' codec on stdout. Try:

```
output {
  stdout { codec => rubydebug }
}
```

and let us know if that works or not.

**Comment by andrewvc** [comment]
No response, closing.
