### ISSUE TITLE
How To Set Heartbeat?

### ISSUE THREAD

**Issue by micahasmith** [logstash-plugins/logstash-input-rabbitmq#41]
I would like to be able to set [heartbeat](https://www.rabbitmq.com/heartbeats.html).

[the config for hare is here, i think](https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/session.rb#L66)

Possible with the latest version?

**Comment by markwalkom** [comment]
Per [the docs](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-rabbitmq.html), we don't currently have that exposed.

**Comment by michaelklishin** [comment]
@markwalkom it would be great to have that configurable for the plugin.

**Comment by micahasmith** [comment]
for real. totally keeps me from being able to keep the service up in production.

until then:

```bash
# sudo crontab -e and add to end of file
* * * * * timeout 60s /var/logstash-1.5.4/bin/logstash -f /var/logstash-1.5.4/logstash.conf
```

**Comment by andrewvc** [comment]
@micahasmith I'm planning on adding this in the next few weeks. If you'd like to get to it sooner we'd be glad to accept a patch! If anyone would like to submit a PR to the rabbitmq_connection mixin (where shared logic for the input and output goes), I've opened up an issue here: https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/blob/master/lib/logstash/plugin_mixins/rabbitmq_connection.rb

**Comment by michaelklishin** [comment]
@micahasmith you can also configure default heartbeat in the server, or disable them entirely by setting the value to `0`.

**Comment by micahasmith** [comment]
@michaelklishin you have no idea the kind of headaches this solves for me 

made my /etc/rabbitmq/rabbitmq.config file:

```
[
	{rabbit, [{heartbeat, 20}]}
].
```

**Comment by andrewvc** [comment]
This has been merged into the common connection logic. Heartbeat + connection_timeout will be configurable in the the next logstash 2.0 beta release, or by using the 2.0 beta and bumping the version of `logstash-mixin-rabbitmq_connection`.

Thanks so much for reporting this @micahasmith , and thanks @michaelklishin for the workaround!
