### ISSUE TITLE
Upgrade to March Hare 2.16.0

### ISSUE THREAD

**Issue by michaelklishin** [logstash-plugins/logstash-input-rabbitmq#42]
[Release notes](http://blog.rubyrabbitmq.info/blog/2015/10/03/march-hare-2-dot-13-dot-0-is-released/).

**Comment by suyograo** [comment]
@michaelklishin thanks.. any idea if this memory leak: https://github.com/elastic/logstash/issues/3992 has been fixed by 2.13.0? Also see #17

**Comment by michaelklishin** [comment]
@suyograo I don't see any evidence that the issue you've linked to has anything to do with March Hare. Heap breakdown suggests most memory is taken by threads managed by Logstash's input, not March Hare or RabbitMQ Java client.

**Comment by michaelklishin** [comment]
@suyograo I've left a comment in the issue. The plugin probably doesn't acknowledge messages correctly (or at all) when [manual delivery acknowledgements](http://rubymarchhare.info/articles/queues.html) are used.

**Comment by suyograo** [comment]
thanks much @michaelklishin

**Comment by magnusbaeck** [comment]
logstash-input-rabbitmq had march_hare upgraded in #55, which brought in logstash-mixin-rabbitmq_connection v2.3.0, which includes https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/13, which bumps march_hare from 2.11.0 to 2.15.0. Close this issue?

**Comment by michaelklishin** [comment]
@magnusbaeck March Hare 2.16 is out ;)

**Comment by andrewvc** [comment]
This was fixed long ago. We are currently on 2.19.0
