### ISSUE TITLE
Align "threads" with other plugins

### ISSUE THREAD

**Issue by markwalkom** [logstash-plugins/logstash-input-rabbitmq#43]
What is referred to as a `worker` in this plugin is a `thread` in others, it'd be good if we aligned this with the majority.

https://www.elastic.co/guide/en/logstash/current/plugins-inputs-rabbitmq.html#plugins-inputs-rabbitmq-threads

eg in the associated output plugin - https://www.elastic.co/guide/en/logstash/current/plugins-outputs-rabbitmq.html#plugins-outputs-rabbitmq-workers

**Comment by andrewvc** [comment]
@markwalkom can you reopen this in logstash/core ? This is actually an issue with the input plugin base class.
