### ISSUE TITLE
Logstash crash + rabbitmq input ( queue )

### ISSUE THREAD

**Issue by quejinho1988** [logstash-plugins/logstash-input-rabbitmq#44]
When my rabbitmq does have for example 5k of messages in queue 
and i run my logstash 1.5.4 and do kill -9 as soon as messages start comming i lose about 1k of messages. No errors what so ever in logs.

**Comment by michaelklishin** [comment]
@quejinho1988 you need to enable manual message acknowledgements so that "in flight" messages (consumed but not stored in ES) are re-queued.

**Comment by andrewvc** [comment]
This has been resolved via @michaelklishin 's answer. Thanks! If you continue have issues please open a new ticket.
