### ISSUE TITLE
Logstash 2.0.0 crashes if exchange doesn't exist

### ISSUE THREAD

**Issue by ThomasdOtreppe** [logstash-plugins/logstash-input-rabbitmq#48]
I have logstash pull data from a bunch of RabbitMQ. If for whatever reason, on one of the RabbitMQ, the exchange doesn't exist, logstash crashes with the following vague message (in my case, I called the exchange 'logstash'):

```
{:timestamp=>"2015-11-04T13:18:12.208000-0700", :message=>"The error reported is: \n  NOT_FOUND - no exchange 'logstash' in vhost '/'"}
```

If it's any useful, here is the config:
```
input {
        # Some info
        rabbitmq {
                queue => "logstash_queue"
                host => "10.0.0.200"
                exchange => "logstash"
        }
}
```

Logstash shouldn't crash due to that issue. It should keep trying (like when it fails to connect to it).

I don't remember having this issue on 1.5.X.

System info:
- Ubuntu 14.04.3 LTS 64 bit
- Logstash 2.0.0 from Elastic repositories.
- RabbitMQ from Ubuntu repositories (the system on which they run is also using Ubuntu 14.04.3 LTS 64 bit).

**Comment by andrewvc** [comment]
Thanks for reporting this @ThomasdOtreppe ! I'll take a look sometime this week

**Comment by gromit6891** [comment]
Any updates on this?

**Comment by ThomasdOtreppe** [comment]
Any update? This is a pretty serious bug.

**Comment by michaelklishin** [comment]
What do you mean by "crashes", does the entire JVM process terminate?

**Comment by ThomasdOtreppe** [comment]
Yes.

**Comment by andrewvc** [comment]
@ThomasdOtreppe I'll try and take a look tomorrow.

@michaelklishin your thoughts? Should we be handling this differently at the Logstash level?

**Comment by michaelklishin** [comment]
@andrewvc declare things that do not exist?

**Comment by smetj** [comment]
@andrewvc a good behaving amqp client should declare missing exchanges, queues and bindings and that's what the logstash rabbitmq input also should do.

I also ran into this issue

Besides that, the "exchange_type" parameter seems to be optional, whilst for the output plugin it is an obligatory parameter. Not a huge problem as such, but both input & output rabbitmq plugins should have the same behavior in this regard.

**Comment by ThomasdOtreppe** [comment]
@andrewvc Have you had a chance to test?

**Comment by andrewvc** [comment]
@smetj @ThomasdOtreppe thanks for your input, I have a patch up here: https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/48

I'm hoping to merge it and release it soon.

**Comment by andrewvc** [comment]
@smetj @ThomasdOtreppe correction, the patch is here: https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/72
