### ISSUE TITLE
Improve error message when exchange does not exist

### ISSUE THREAD

**Issue by ThomasdOtreppe** [logstash-plugins/logstash-input-rabbitmq#49]
When an exchange doesn't exist, logstash crashes (#48) and it gives a pretty vague error message (in my case the exchange was called 'logstash'):

```
{:timestamp=>"2015-11-04T10:22:30.522000-0700", :message=>"The error reported is: \n  NOT_FOUND - no exchange 'logstash' in vhost '/'"}
```

It's kinda easy to figure out when you have one RabbitMQ but if you have no idea, the message is pretty useless. The following information needs to be added for clarity:
- It should say it's RabbitMQ.
- It should tell which host (and port).

**Comment by yaauie** [comment]
It looks like the current `declare_exchange!` has significantly better log messaging, so I'm closing this issue.

See: https://github.com/logstash-plugins/logstash-integration-rabbitmq/blob/v7.0.1/lib/logstash/plugin_mixins/rabbitmq_connection.rb#L190-L193
