### ISSUE TITLE
prefetch_count doesnt seem to have any effect

### ISSUE THREAD

**Issue by adfel70** [logstash-plugins/logstash-input-rabbitmq#50]
It seems that prefetch_count never being set, even not the default value of 256 - our consumers connect to Rabbit with prefetch=0 since the upgrade to 3.0.3.

**Comment by cFire** [comment]
+1 I also just noticed this behavior after upgrading LS from 1.5 to 2.0 branch.

**Comment by tparker00** [comment]
It looks like this is related to logstash-mixin-rabbitmq_connection, reverting to 6edc495 resolved it for me.

**Comment by andrewvc** [comment]
This should be fixed now as of https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/46/files

Please reopen this if you continue to encounter issues.
