### ISSUE TITLE
Consumer cancel notification is not handled

### ISSUE THREAD

**Issue by aseppala** [logstash-plugins/logstash-input-rabbitmq#51]
When RabbitMQ server sends a consumer cancel notification (https://www.rabbitmq.com/consumer-cancel.html) the plugin stops consuming the queue, but leaves connections and channels open. This results process going in a limbo state where logstash is up and running, but rabbitmq input plugin does not consume from the queue.

I'm not sure what would be the correct way to recover from this situation, I just wanted to raise the issue.

**Comment by aseppala** [comment]
I was able to fix this by defining a callback for on_cancellation and call stop from there:

```
--- a/lib/logstash/inputs/rabbitmq.rb
+++ b/lib/logstash/inputs/rabbitmq.rb
@@ -87,7 +87,7 @@ module LogStash
       def consume!
         # we manually build a consumer here to be able to keep a reference to it
         # in an @ivar even though we use a blocking version of HB::Queue#subscribe
-        @consumer = @hare_info.queue.build_consumer(:block => true) do |metadata, data|
+        @consumer = @hare_info.queue.build_consumer(:block => true, :on_cancellation =>Proc.new { stop }) do |metadata, data|
           @codec.decode(data) do |event|
             decorate(event)
             @output_queue << event if event
```

While this fix is very straight forward, it doesn't give any hints to the user why we exit the process. Any comments?

**Comment by michaelklishin** [comment]
`basic.cancel` coming from the server does include a reason but your proc ignores the argument.

**Comment by aseppala** [comment]
Yes, you can get channel, self and consumer tag to the callback if wanted (https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/consumers/base.rb#L34). However I'm not sure if there are any meaningful values to log.

How about logging something like

```ruby
@logger.info("Reveived basic.cancel from #{rabbitmq_settings[:host]}, shutting down.")
```

Then the logstash output would look something like this with *--verbose*:
```
Connected to RabbitMQ at rabbitmq {:level=>:info}
Logstash startup completed
Reveived basic.cancel from rabbitmq, shutting down. {:level=>:info}
Pipeline shutdown complete. {:level=>:info}
Logstash shutdown completed
```
Also, should I make a pull request with a proposed fix? Or could you resolve this yourself as I'm not really a ruby developer.

**Comment by michaelklishin** [comment]
@aseppala yeah, I thought of `connection.close` for a second, which can also be server-sent :) your suggestion makes sense, logging is a good idea. However, I'm not sure if shutting down is the only reasonable strategy. Clients can re-declare their queue(s) and start consuming again.

**Comment by aseppala** [comment]
It could be reasonable. Then if the node(s) that should host the queue (by HA policy or statically configured) are still parted from the cluster, we will get an error:

```
The error reported is:
  NOT_FOUND - home node 'rabbit@rabbit1' of durable queue 'my-queue' in vhost '/' is down or inaccessible
```

And that will result also in shutting down.

**Comment by michaelklishin** [comment]
If a queue is mirrored, a new master will be elected (and consumers will be re-registered for you, in fact), so normally the above is only the case with non-mirrored durable queues. Non-durable queues will also be migrated.

**Comment by michaelklishin** [comment]
@andrewvc the above suggestion makes sense to me. Would you folks consider it?

**Comment by andrewvc** [comment]
@aseppala @michaelklishin thanks so much for the enlightening discussion above :).

I'd gladly accept a patch that stopped the plugin in that scenario.

It sounds like there are a range of acceptable behaviors on `cancel`.

1. Log a warning and stop the plugin
2. Attempt to restart the consuming (maybe we could have a `restart_on_cancelled_after` option?
3. Log a warning and do nothing

It sounds like you're proposing 1. @aseppala is that correct? In a perfect world we'd let the user pick either 1. or 2., but I'd gladly accept a patch for 1. if that's all you're up for @aseppala .

Please let me know if I've understood all the issues here correctly!

**Comment by aseppala** [comment]
Yes, 1. would be the easiest to implement and solves the issue for people who use some sort of supervisor to keep their logstashes alive.

However 2. would probably be better solution in the long term, but my knowledge on ruby is very limited and wouldn't like to spend too much time on this.

I can start crafting a pr for 1. fix and start the CLA process as well.

**Comment by aseppala** [comment]
CLA has been signed and I started to work on this again. However, I'm having trouble setting up a working dev env and to run tests. I'm stuck with this error, any ideas?

```
$ bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find gem 'logstash-devutils' in any of the gem sources listed in your Gemfile or available on this machine.
```

**Comment by aseppala** [comment]
Got it. I didn't have jruby activated. I'll close this issue and open a PR.
