### ISSUE TITLE
Logstash not sending Acknowledge, after connection problems

### ISSUE THREAD

**Issue by nazim9214** [logstash-plugins/logstash-input-rabbitmq#52]
When between logstash and rabbitmq server occurs connection problem, logstash not send Acknowledge to rabbitmq server.But I see corresponding connection on the rabbitmq connections list, and server tries send messages to client. Manually closing this connection from server side does not resolves issue.

**Comment by michaelklishin** [comment]
@nazim9214 the client reconnects. By acknowledgement do you mean consumer or publisher ones? You can inspect if manual acknowledgements are used by consumers e.g. in the management UI.

**Comment by nazim9214** [comment]
I'm sorry, it seems this is more due to the heartbeat option
