### ISSUE TITLE
Provide an error message when RabbitMQ instance is not available.

### ISSUE THREAD

**Issue by sherry-ger** [logstash-plugins/logstash-input-rabbitmq#60]
LS version 2.1

When a RabbitMQ instance is unavailable and LS cannot connect to it, LS shows the following messages.

```
{:timestamp=>"2016-01-21T17:05:03.246000-0800", :message=>"The error reported is: \n "} 
{:timestamp=>"2016-01-21T17:05:09.104000-0800", :message=>"The error reported is: \n "} 
{:timestamp=>"2016-01-21T17:05:14.827000-0800", :message=>"The error reported is: \n "} 
{:timestamp=>"2016-01-21T17:05:20.675000-0800", :message=>"The error reported is: \n "}
```

The error messages seem to be available once DEBUG was enabled.  Please add the actual error message.  Perhaps, this is related to https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/49.

**Comment by yaauie** [comment]
It looks like the connection error messaging has significantly improved since this issue was originally raised, so I think it can be closed.
