### ISSUE TITLE
New consumer created after each RabbitMQ restart

### ISSUE THREAD

**Issue by benimurza** [logstash-plugins/logstash-input-rabbitmq#66]
Given: 

- Logstash with RabbitMQ input plugin 3.1.4 (installed as service with nssm)

- RabbitMQ (installed as service)

Problem: after each RabbitMQ service restart, a new consumer tag is created. What this means: at first, every message sent to logstash is received (and written in elasticsearch, in my case). After a RabbitMQ restart, only every 2nd message is written in elasticsearch, the other will remain in the queue, unacknowdledged. After another restart, only every 3rd message will show up in elasticsearch, the other 2 will remain unacknowdleged in the queue. And so on.

Here's my config:

`input {`
    `    rabbitmq {`
		`host => "localhost"`
		`user => "***"`
		`password => "***"`
		`key => "TestRoutingKey.#"`
		`exchange => "amq.topic"`
		`auto_delete => "false"`
		`durable => "true"`
		`type => "RabbitMQSource"`
		`queue => "ReconnectTestQueue"`
	`}`

And [here](http://pasteboard.co/1EiT9Ws5.jpg)'s how the Queue from which Logstash consumes looks like, after three RabbitMQ server restarts.

**Comment by andrewvc** [comment]
@benimurza Thank you for reporting this. This must be related to https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/64 . @michaelklishin if I had to guess on reconnect the consumer is re-established but the block is just not ever called again.

**Comment by andrewvc** [comment]
@benimurza when https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/68 is merged that should fix the issue!
