### ISSUE TITLE
Allow Multiple Hosts

### ISSUE THREAD

**Issue by Jakauppila** [logstash-plugins/logstash-input-rabbitmq#77]
So this may just be how we have our logging infrastructure structured, but I'd figure I'd toss it out there for discussion. 

We use NXLog to ship from our application servers to a Logstash collector which then routes the events based on log type and version to their own queue within RabbitMQ local on the server. We have one collector per datacenter that balance the load via geographical DNS resolution (so application servers write to the collector in their DC).

On the indexing side, we currently have 2 servers that read from both RabbitMQ instances. The configurations are identical and how the inputs are currently defined, we have to specify them twice (one for each host).

```
rabbitmq {
	codec => "json"
	host => "broker1.contoso.com"
	port => "5671"
	ssl => "true"
	vhost => "logging"
	queue => "software.dotnet.iis.access.v1"
	passive => "true"
	tags => ["software","dotnet","iis","access_logs","unprocessed"]
	type => "iis_access_v1"
}

rabbitmq {
	codec => "json"
	host => "broker2.contoso.com"
	port => "5671"
	ssl => "true"
	vhost => "logging"
	queue => "software.dotnet.iis.access.v1"
	passive => "true"
	tags => ["software","dotnet","iis","access_logs","unprocessed"]
	type => "iis_access_v1"
}
```

Ideally, I'd like to be able to pass in an array for the host(s) value, since the rest of the values are identical.
```
rabbitmq {
	codec => "json"
	hosts => ["broker1.contoso.com","broker2.contoso.com"]
	port => "5671"
	ssl => "true"
	vhost => "logging"
	queue => "software.dotnet.iis.access.v1"
	passive => "true"
	tags => ["software","dotnet","iis","access_logs","unprocessed"]
	type => "iis_access_v1"
}
```

Thoughts?

**Comment by ebuildy** [comment]
Could be hard, since this plugin relies on https://github.com/rabbitmq/rabbitmq-java-client which not support this.

You could use HAProxy between?

**Comment by andrewvc** [comment]
This is now possible though our docs are not yet updated. See https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/commit/21b121c83f8cb84265fa9788147aa87b90e0299a#diff-5a4e6da9864c64f906837378a6f551e6R21
