### ISSUE TITLE
No meta on messages

### ISSUE THREAD

**Issue by MagicMicky** [logstash-plugins/logstash-input-rabbitmq#78]
It seems that I can't get the meta from rabbitmq. I configured the input plugin to connect to an exchange, and used the `metadata_enabled` field to let the plugin add messages metadata.

But both on stdout and kibana from my elk stack, I can't find any `@metdata`  field.

Here is my config : 
```
input {
 rabbitmq {
   queue => "my_queue"
   host => "myhost"
   port => 8000
   vhost => "/dev"
   exchange => "exchange" # This matches the exchange declared above
   type => "actions"
   metadata_enabled => true
  }
}
output {
  elasticsearch {
    hosts => "elasticsearch:9200"
  }
  stdout { codec => rubydebug  }
}
```

```bash
> logstash-plugin list --verbose logstash-input-rabbitmq
logstash-input-rabbitmq (4.0.1)
```

**Comment by suyograo** [comment]
@MagicMicky `@metadata` is only available in the runtime of the pipeline and will not be persisted to outputs. You will have to explicitly copy them to another field, if you need them in Kibana/stdout

See: https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#metadata
