### ISSUE TITLE
Rabbitmq input plugin doesn't recover when exchange is not found

### ISSUE THREAD

**Issue by parabolic** [logstash-plugins/logstash-input-rabbitmq#80]
Hi,
I am having this issue with the latest rabbitmq input plugin. I've been using logstash version 2.2.2 for some time now and Yesterday I decided to bump the version to the latest 2.3.2. The problem that I am experiencing is that the input plugin doesn't want to reconnect to the queue after the exchange has been created. So it goes like this  
1. logstash with rabbitmq input (configuration is below! ) connects to rabbitmq and the exchange is not there.
2. exchange gets created in the meantime and logstash input plugin is still not working and the error message wihch is below can be seen every 1 second.
3. I initiate a logstash restart and everything works perfect.
Here's the message that I see in the logs.

```
{:timestamp=>"2016-04-28T13:08:27.248000+0000", :message=>"#method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'logstash-rabbitmq' in vhost '/', class-id=50, method-id=20)", :class=>"MarchHare::ChannelAlreadyClosed", :location=>"/opt/logstash-sender/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", :level=>:warn}
```

Logstash version 2.2.2 and logstash-input-rabbitmq (3.1.4) work perfectly fine. I can also see that any logstash version bigger than 2.2.2. is uing the version 4.0.1 of the  logstash-input-rabbitmq plugin. March_hare ( march_hare (~> 2.15.0) ) is the same version up to logstash 2.3.2  
Please advise,
Nikola.
- Version: 
  - logstash-2.3.2
  - logstash-input-rabbitmq (4.0.1)
  - rabbitmq-server                  3.6.1-1
  - march_hare (~> 2.15.0)
- Operating System: 
  - Ubuntu 14.04.4 LTS
- Config File:

```
input   {
  rabbitmq {
    host      => '127.0.0.1'
    port      =>  5673
    ack       =>  true
    exchange  =>  'logstash-rabbitmq'
    queue     =>  'logstash'
    durable   =>  true
    threads   =>  10
  }
}
```
- Sample Data:

```
{:timestamp=>"2016-04-28T13:08:27.248000+0000", :message=>"#method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'logstash-rabbitmq' in vhost '/', class-id=50, method-id=20)", :class=>"MarchHare::ChannelAlreadyClosed", :location=>"/opt/logstash-sender/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", :level=>:warn}
{:timestamp=>"2016-04-28T13:08:28.249000+0000", :message=>"#method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'logstash-rabbitmq' in vhost '/', class-id=50, method-id=20)", :class=>"MarchHare::ChannelAlreadyClosed", :location=>"/opt/logstash-sender/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", :level=>:warn}
```
- Steps to Reproduce:
  - Every time I spin up a new instance

**Comment by michaelklishin** [comment]
You are hitting a channel exception, not a connection one. Those are *not* automatically recovered from, by design: they an indicate an application or environment error. In your case Logstash tries to publish to an exchange that does not exist.

**Comment by parabolic** [comment]
@michaelklishin 
thanks for the fast reply but how is it working in 2.2.2 and I am not getting that exception ?

**Comment by michaelklishin** [comment]
@parabolic I know nothing about your environment. It could be a behaviour change in this project. My remark was about the way RabbitMQ client libraries work, including the one that's used by this plugin.

Anyhow, this issue certainly has a workaround: declare the exchange.

**Comment by michaelklishin** [comment]
Also: I primarily wanted to point out that according to the log provided, there are NO issues with the connection, it's the channel that is closed (because of a "not found" protocol exception). So the title of this issue as it is right now is misleading.

**Comment by parabolic** [comment]
Ok, that was the only fix I could think of anyway. 
I will give you some insight on how I use it.
Logstash rabbitmq-output ( creates the queue, and exchange and puts messages to the queue ) -> Rabbitmq <- Loggstash rabbitmq input ( consumes message ).
Both logstashes are separate service on one machine so I get a queue sandwich of :
logstash-rabbitmq-logstash
The logstash consumer connects to rabbitmq , it doesn't finds the exchange and it cannot recover from that point onwards. I do not see the same issue with verison 2.2.2
Hope this is clearer.

**Comment by parabolic** [comment]
@michaelklishin 
just to let you know that I was able to solve the issue by predefining the exchange and queue before logstash starts working.
I  can safely close this one or leave it open that's up to you.

Thanks for the support and cheers!

**Comment by wmosher** [comment]
I am also having this new issue after upgrading from logstash 1.5 to 2.3.  In our environments logstash starts before our applications and our applications create the exchanges.  I can definitely pre-create the exchange as @parabolic noted, but it definitely didn't work this way previously and isn't ideal.

In the 1.5 version we expectedly see these errors for a bit, and then they stop once the applications have created the exchange, a consumer shows up on the expected queue, and we start getting data in es/kibana.

```
{:timestamp=>"2016-08-12T16:08:52.449000+0000", :message=>"RabbitMQ connection error: NOT_FOUND - no exchange 'logging.x' in vhost '/'. Will reconnect in 10 seconds...", :level=>:error}
```

In the 2.3 version it just endlessly reports the following, even after the exchange has shown up, and it never recovers.

```
{:timestamp=>"2016-08-12T16:23:44.815000+0000", :message=>"#method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'logging.x' in vhost '/', class-id=50, method-id=20)", :class=>"MarchHare::ChannelAlreadyClosed", :location=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.15.0-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", :level=>:warn}
```

**Comment by digitalkaoz** [comment]
@michaelklishin how to recover channel exceptions (haproxy kill the tcp connection due to a restart) then? why those are not recovered by design? the logstash plugin should try at least

**Comment by andrewvc** [comment]
Hmmm, the output *should* declare the exchange on boot: https://github.com/logstash-plugins/logstash-output-rabbitmq/blob/master/lib/logstash/outputs/rabbitmq.rb#L41

I'll look into why it isn't doing that.

**Comment by bheuvel** [comment]
Perhaps I'm confused, by the last comment on `output`, but I had the same problem where we spin up a collection of containers, where logstash is quicker then our application, thereby the exchange not yet created in rabbitmq, thereby logstash never "recovering".

But the comment on output made me look at the **input** source, where I spotted the _hidden_ feature:
https://github.com/logstash-plugins/logstash-input-rabbitmq/blob/master/lib/logstash/inputs/rabbitmq.rb#L198
```
if @exchange_type # Only declare the exchange if @exchange_type is set!
```

So as an example:
```
input   {
  rabbitmq {
...
    exchange  =>  'logstash-rabbitmq'
    exchange_type => 'direct'
...
  }
}
```
got me:
```
{:timestamp=>"2016-12-07T15:10:43.170000+0000", :message=>"Declaring exchange 'logstash-rabbitmq' with type direct", :level=>:info, :file=>"logstash/inputs/rabbitmq.rb", :line=>"196", :method=>"bind_exchange!"}
```

Unfortunately `exchange_type` is not mentioned in the documentation: https://www.elastic.co/guide/en/logstash/5.0/plugins-inputs-rabbitmq.html

Hope this works for you too, @parabolic @wmosher

**Comment by andrewvc** [comment]
Thanks for reporting the issue @bheuvel . I'll try and get that docs page updated. The doc generation still has some issues, but we're working on making it update automatically.

**Comment by andrewvc** [comment]
@bheuvel looks like the docs were fixed a while back! Please open a new issue if you have a new concern :) Thanks for the report!
