### ISSUE TITLE
Java::JavaIo::IOException on vhost access restriction

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [logstash-plugins/logstash-input-rabbitmq#81]
When connecting to a RabbitMQ server, and attempting to access a queue on a vhost to which you have not been granted access, you get an IOException instead of a decent explanation:

```
Connecting to RabbitMQ. Settings: {:vhost=>"/", :host=>"max", :port=>5671, :user=>"user", :automatic_recovery=>true, :pass=>"pass", :timeout=>0, :heartbeat=>0} {:level=>:debug, :file=>"logstash/plugin_mixins/rabbitmq_connection.rb", :line=>"138", :method=>"connect"}
 {:class=>"Java::JavaIo::IOException", :location=>"com.rabbitmq.client.impl.AMQChannel.wrap(com/rabbitmq/client/impl/AMQChannel.java:106)", :level=>:warn, :file=>"logstash/inputs/rabbitmq.rb", :line=>"180", :method=>"register"}
```

**Comment by michaelklishin** [comment]
March Hare wraps certain exceptions into Ruby ones but not all of them. This project should not be concerned with Java client to Ruby exception conversion, [March Hare](https://github.com/ruby-amqp/march_hare) should.

**Comment by andrewvc** [comment]
Closing due to @michaelklishin 's point. I think this was already fixed since then anyway.
