### ISSUE TITLE
Rescue java.io.IOError on consumer cancel

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-input-rabbitmq#87]
Currently in bizarre situations a consumer cancel can fail if there is a missing consumer tag. Why this would happen, I do not know, but it has happened. See https://www.rabbitmq.com/releases/rabbitmq-java-client/v2.8.2/rabbitmq-java-client-javadoc-2.8.2/com/rabbitmq/client/Channel.html#basicCancel(java.lang.String)

**Comment by michaelklishin** [comment]
It can fail because the consumer was already cancelled either by a client or, for example, because consumer's queue was deleted/expired. It will also fail if you try cancelling a consumer on a different channel.

**Comment by andrewvc** [comment]
Thanks for the background @michaelklishin !

**Comment by andrewvc** [comment]
Fixed in https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/commit/4cfc15677de673180489371cd86a970a5a450f21
