### ISSUE TITLE
Message(s) repeatedly being loaded from/into queue

### ISSUE THREAD

**Issue by Signus** [logstash-plugins/logstash-input-rabbitmq#90]
Single or multiple messages are being grabbed from the queue correctly, however they are not appropriately being dequeued, and the same message is loaded from the queue repeatedly by the `logstash-input-rabbitmq` plugin, creating thousands of duplicates.

**Note**: Even after the message is removed from the queue (either by requeue:false or purging the queue, it appears `logstash-input-rabbitmq` is still inserting the message back into the queue so long as Logstash is running.

- Version(s): 
    - 4.0.4
    - 4.1.0
    - 5.1.1
- Operating System:
    - CentOS 7 x64

Config File:

```
input {
    rabbitmq {
        host => "ipaddress"
        vhost => "vhost1"
        exchange => "temp_exchange"
        #exchange_type => "direct"
        queue => "temp_queue"
        key => "key"
        #auto_delete => false
        durable => true
        passive => true
        user => "user"
        password => "password"
        port => 5672
        metadata_enabled => true
    }
}
output {
    stdout { codec => rubydebug }
    # using tcp output shows same results
}
```

Sample Data:

The original message is just a simple line of test data: `some_field=1234 test_field=testing1234`

Output:

```
{
       "message" => "some_field=1234 test_field=testing1234",
      "@version" => "1",
    "@timestamp" => 2016-08-08T08:01:11.532Z,
          "host" => "host",
          "port" => 51901
}
{
       "message" => "some_field=1234 test_field=testing1234",
      "@version" => "1",
    "@timestamp" => 2016-08-08T08:01:11.532Z,
          "host" => "host",
          "port" => 51901
}
{
       "message" => "some_field=1234 test_field=testing1234",
      "@version" => "1",
    "@timestamp" => 2016-08-08T08:01:11.532Z,
          "host" => "host",
          "port" => 51901
}
...
```

With metadata:

```
{
    "message" => "some_field=1234 test_field=testing1234",
    "@version" => "1",
    "@timestamp" => 2016-08-08T08:01:11.532Z,
    "host" => "host",
    "port" => 51901,
    "@metadata" => {
        "rabbitmq_headers" => {},
        "rabbitmq_properties" => {
            "delivery-mode" => 2,
            "exchange" => "temp_exchange",
            "routing-key" => "key",
            "consumer-tag" => "amq.ctag-zKsDzzlzNb84Qxq-fr83b1"
        }
    }
}
```

Where the output being printed is continuous, so long as the process is running. This happens for all events in the specified queue (i.e. for 55 events all 55 events are repeatedly read and published back into the queue).

- Steps to Reproduce:
    - Insert single test message into RabbitMQ queue
    - Turn on Logstash instance with supplied configuration

Queue statistics:

![screen shot 2016-08-08 at 11 51 54 am](https://cloud.githubusercontent.com/assets/3129598/17490292/63aced62-5d5f-11e6-9cc6-bbcf0854ec9e.png)

**Comment by michaelklishin** [comment]
You see that the message is being re-queued and redelivered. Most likely the output fails with an exception. See Logstash logs.

**Comment by Signus** [comment]
I did check that, however there are zero exceptions that occur during this process.

I would also imagine if that were true, then when I utilize `output-tcp`, I would never see those logs on the other system. The behavior for stdin and tcp outputs are the exact same.

**Comment by Signus** [comment]
False alarm - an old configuration utilizing the `logstash-output-rabbitmq` plugin was running on the same system under a different instance, meaning that everything that was being grabbed by RabbitMQ was immediately being re-entered into RabbitMQ.
