### ISSUE TITLE
RabbitMQ Input Plugin Blocks Logstash Pipeline Start 

### ISSUE THREAD

**Issue by jcarterch** [logstash-plugins/logstash-input-rabbitmq#91]
As per discussion here https://github.com/elastic/logstash/issues/4931 , logstash starts all input plugins one by one. If the rabbit input plugin is attempting to connect to a rabbit node that is unavailable, the plugin blocks, and logstash is unable to start and initialize the pipeline. This is contrary to the redis plugin for example, which will attempt to reconnect and not block pipeline startup. 

Is it possible to change the input plugin to not block startup on a connection failure, but initialize and attempt to reconnect according to connect_retry_interval?

**Comment by andrewvc** [comment]
This should be a relatively easy fix. I'll try to find some time to do this.

**Comment by jcarterch** [comment]
Thanks for the quick turnaround on this @andrewvc! Tested and it worked nicely.
