### ISSUE TITLE
Plugin is not converting values to a supported type

### ISSUE THREAD

**Issue by jjfalling** [logstash-plugins/logstash-input-rabbitmq#94]
- Version:  LS 5.1.1, OpenJDK 1.8.0_111
- Operating System: CentOS 7.2
- Config: (below)

The RabbitMQ input is 'leaking' this value into the Event.set(..) without converting it to a supported type. `com.rabbitmq.client.impl.LongStringHelper$ByteArrayLongString` needs to be converted to a Java or Ruby string before setting it in the Event. This seems to only occur when metadata_enabled is true. 

`14:26:21.412 [[main]<rabbitmq] ERROR logstash.pipeline - A plugin had an unrecoverable error. Will restart this plugin.
 Plugin: <LogStash::Inputs::RabbitMQ host=>["im-ea04.wintech.local"], user=>"ES", password=><password>, vhost=>"/", queue=>"Message.Audit.Error.LogToElasticsearch", exclusive=>false, durable=>true, auto_delete=>false, metadata_enabled=>true, type=>"alphaaudit", codec=><LogStash::Codecs::Plain id=>"plain_984c5870-b863-42a7-94d4-a46adde673f0", enable_metric=>true, charset=>"UTF-8">, tags=>["Error"], id=>"64f2c248ae8409f08679b327a3c6bdc8b6af9462-2", enable_metric=>true, debug=>false, threads=>1, port=>5672, ssl_version=>"TLSv1.2", automatic_recovery=>true, connect_retry_interval=>1, passive=>false, prefetch_count=>256, ack=>true, key=>"logstash", subscription_retry_interval_seconds=>5>
 Error: Missing Valuefier handling for full class name=com.rabbitmq.client.impl.LongStringHelper$ByteArrayLongString, simple name=ByteArrayLongString
 Exception: Java::JavaLang::IllegalArgumentException
 Stack: org.logstash.Valuefier.convertNonCollection(Valuefier.java:51)`

Config:
  rabbitmq {
    host             => "rabbitmq-host"
    user             => "username"
    password         => "password"
    vhost            => "/"
    queue            => "lsqueue"
    exclusive        => false
    durable          => true
    auto_delete      => false
    metadata_enabled => true
    type             => "logging"
    codec            => "plain"
    tags             => "Error"
  }

**Comment by guyboertje** [comment]
@andrewvc its seems like this line https://github.com/logstash-plugins/logstash-input-rabbitmq/blob/master/lib/logstash/inputs/rabbitmq.rb#L317
is not detecting the Java type correctly.
